const SEARCH_FOR_AN_OPPONENT = "SEARCH_FOR_AN_OPPONENT";
const OPPONENT_FOUND = "OPPONENT_FOUND";
const OPPONENT_NOT_FOUND = "OPPONENT_NOT_FOUND";
const ERROR_SAVING_GAME = "ERROR_SAVING_GAME";
const PLAYER_LEFT_MATCH_FROM_CLIENT = "PLAYER_LEFT_MATCH_FROM_CLIENT";
const OPPONENT_LEFT_MATCH_FROM_SERVER = "OPPONENT_LEFT_MATCH_FROM_SERVER";
const CLICKED_ON_CELL_FROM_CLIENT = "CLICKED_ON_CELL_FROM_CLIENT";
const CLICKED_ON_CELL_FROM_SERVER = "CLICKED_ON_CELL_FROM_SERVER";
const WINNER_NOTIFICATION_FROM_CLIENT = "WINNER_NOTIFICATION_FROM_CLIENT";
const WINNER_NOTIFICATION_FROM_SERVER = "WINNER_NOTIFICATION_FROM_SERVER";
const PLAYER_DONT_WANT_TO_PLAY_AGAIN_FROM_CLIENT = "PLAYER_DONT_WANT_TO_PLAY_AGAIN_FROM_CLIENT";
const PLAYER_DONT_WANT_TO_PLAY_AGAIN_FROM_SERVER = "PLAYER_DONT_WANT_TO_PLAY_AGAIN_FROM_SERVER";
const PLAYER_WANT_TO_PLAY_AGAIN_FROM_CLIENT = "PLAYER_WANT_TO_PLAY_AGAIN_FROM_CLIENT";
const PLAYER_WANT_TO_PLAY_AGAIN_FROM_SERVER = "PLAYER_WANT_TO_PLAY_AGAIN_FROM_SERVER";
const PLAYER_ACCEPT_FOR_REMATCH_FROM_CLIENT = "PLAYER_ACCEPT_FOR_REMATCH_FROM_CLIENT";
const PLAYER_ACCEPT_FOR_REMATCH_FROM_SERVER = "PLAYER_ACCEPT_FOR_REMATCH_FROM_SERVER";
const CREATE_ROOM = "CREATE_ROOM";
const JOIN_ROOM = "JOIN_ROOM";
const ROOM_READY = "ROOM_READY";
const DESTROY_ROOM = "DESTROY_ROOM";


export {
  SEARCH_FOR_AN_OPPONENT,
  OPPONENT_FOUND,
  ERROR_SAVING_GAME,
  OPPONENT_NOT_FOUND,
  PLAYER_LEFT_MATCH_FROM_CLIENT,
  OPPONENT_LEFT_MATCH_FROM_SERVER,
  CLICKED_ON_CELL_FROM_CLIENT,
  CLICKED_ON_CELL_FROM_SERVER,
  WINNER_NOTIFICATION_FROM_CLIENT,
  WINNER_NOTIFICATION_FROM_SERVER,
  PLAYER_DONT_WANT_TO_PLAY_AGAIN_FROM_CLIENT,
  PLAYER_DONT_WANT_TO_PLAY_AGAIN_FROM_SERVER,
  PLAYER_WANT_TO_PLAY_AGAIN_FROM_CLIENT,
  PLAYER_WANT_TO_PLAY_AGAIN_FROM_SERVER,
  PLAYER_ACCEPT_FOR_REMATCH_FROM_CLIENT,
  PLAYER_ACCEPT_FOR_REMATCH_FROM_SERVER,
  CREATE_ROOM,
  JOIN_ROOM,
  ROOM_READY,
  DESTROY_ROOM
};
