const SEARCH_FOR_AN_OPPONENT = "SEARCH_FOR_AN_OPPONENT";
const OPPONENT_FOUND = "OPPONENT_FOUND";
const OPPONENT_NOT_FOUND = "OPPONENT_NOT_FOUND";
const ERROR_SAVING_GAME = "ERROR_SAVING_GAME";
const OPPONENT_LEFT_MATCH = "OPPONENT_LEFT_MATCH";
const CLICKED_ON_CELL_FROM_CLIENT = "CLICKED_ON_CELL_FROM_CLIENT";
const CLICKED_ON_CELL_FROM_SERVER = "CLICKED_ON_CELL_FROM_SERVER";
const WINNER_NOTIFICATION_FROM_CLIENT = "WINNER_NOTIFICATION_FROM_CLIENT";
const WINNER_NOTIFICATION_FROM_SERVER = "WINNER_NOTIFICATION_FROM_SERVER";
const PLAYER_DONT_WANT_TO_PLAY_AGAIN = "PLAYER_DONT_WANT_TO_PLAY_AGAIN";
const PLAYER_WANT_TO_PLAY_AGAIN = "PLAYER_WANT_TO_PLAY_AGAIN";

export {
  SEARCH_FOR_AN_OPPONENT,
  OPPONENT_FOUND,
  ERROR_SAVING_GAME,
  OPPONENT_NOT_FOUND,
  OPPONENT_LEFT_MATCH,
  CLICKED_ON_CELL_FROM_CLIENT,
  CLICKED_ON_CELL_FROM_SERVER,
  WINNER_NOTIFICATION_FROM_CLIENT,
  WINNER_NOTIFICATION_FROM_SERVER,
  PLAYER_DONT_WANT_TO_PLAY_AGAIN,
  PLAYER_WANT_TO_PLAY_AGAIN,
};
